apiVersion: v1
kind: Pod
metadata:
   name: glance
spec:
  hostNetwork: True
  containers:
    - image: kollaglue/centos-binary-glance-api:2.0.0
      name: glance-api
      volumeMounts:
        - mountPath: "/var/lib/kolla/config_files"
          name: glance-config
      env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
    - image: kollaglue/centos-binary-glance-registry:2.0.0
      name: glance-registry
      volumeMounts:
        - mountPath: "/var/lib/kolla/config_files"
          name: glance-config
      env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
  volumes:
    - name: glance-config
      hostPath:
        path: "/etc/kolla/keystone"
