apiVersion: v1
kind: Pod
metadata:
   name: mongodb
spec:
  hostNetwork: True
  containers:
    - image: kollaglue/centos-binary-mongodb:2.0.0
      name: mongodb
      volumeMounts:
        - mountPath: "/var/lib/kolla/config_files"
          name: mongodb-config
      env:
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
  volumes:
    - name: mongodb-config
      hostPath:
        path: "/etc/kolla/mongodb"
